# Generated by Django 5.2.1 on 2025-05-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menuitem_options_alter_menuitem_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu_name', 'title'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
    ]
